"""
Research OS - Export Service

Generates Markdown reports, JSON data, CSV paper tables, and BibTeX citations
from completed research run data.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime
from typing import Any
from uuid import UUID

from structlog import get_logger

logger = get_logger(__name__)


async def generate_markdown_report(
    run: dict[str, Any],
    hypotheses: list[dict[str, Any]],
    papers: list[dict[str, Any]],
    events: list[dict[str, Any]],
) -> str:
    """Generate a comprehensive Markdown research report."""
    # Build the report from actual data
    lines = []
    lines.append(f"# Research Report: {run.get('title', 'Untitled')}")
    lines.append("")
    lines.append(f"**Topic:** {run.get('topic', 'N/A')}")
    lines.append(f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Status:** {run.get('status', 'unknown')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"This research run analyzed the topic \"{run.get('topic', '')}\" ")
    lines.append(f"and discovered **{len(papers)}** papers. ")
    verified = [h for h in hypotheses if h.get("status") == "verified"]
    if verified:
        lines.append(f"**{len(verified)}** innovation hypotheses were verified.")
    lines.append("")

    # Statistics
    lines.append("## Statistics")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Papers discovered | {len(papers)} |")
    lines.append(f"| Hypotheses generated | {len(hypotheses)} |")
    lines.append(f"| Hypotheses verified | {len(verified)} |")
    budget = run.get("budget_json", {})
    if isinstance(budget, str):
        try:
            budget = json.loads(budget)
        except (json.JSONDecodeError, TypeError):
            budget = {}
    lines.append(f"| Budget (max papers) | {budget.get('max_new_papers', 'N/A')} |")
    lines.append(f"| Budget (max reads) | {budget.get('max_fulltext_reads', 'N/A')} |")
    lines.append("")

    # Papers Table
    if papers:
        lines.append("## Papers")
        lines.append("")
        lines.append("| # | Title | Year | Venue | Citations |")
        lines.append("|---|-------|------|-------|-----------|")
        for i, p in enumerate(papers[:50], 1):
            title = (p.get("canonical_title") or p.get("title", "Unknown"))[:60]
            year = p.get("publication_year", "?")
            venue = (p.get("venue") or "")[:30]
            cites = p.get("citation_count", 0) or 0
            lines.append(f"| {i} | {title} | {year} | {venue} | {cites} |")
        lines.append("")

    # Hypotheses
    if hypotheses:
        lines.append("## Innovation Hypotheses")
        lines.append("")
        for h in hypotheses:
            status_icon = "[OK]" if h.get("status") == "verified" else "[X]" if h.get("status") == "rejected" else "[?]"
            lines.append(f"### {status_icon} {h.get('title', 'Untitled')}")
            lines.append("")
            lines.append(f"**Type:** {h.get('type', 'unknown')}")
            lines.append(f"**Status:** {h.get('status', 'candidate')}")
            if h.get("statement"):
                lines.append(f"\n{h['statement']}")
            lines.append("")
            scores = []
            for score_name in ("novelty_score", "feasibility_score", "evidence_score", "risk_score"):
                val = h.get(score_name)
                if val is not None:
                    scores.append(f"{score_name.replace('_score','').title()}: {val:.2f}")
            if scores:
                lines.append(f"**Scores:** {' | '.join(scores)}")
            lines.append("")

    # Event Timeline (last 20)
    if events:
        lines.append("## Event Timeline")
        lines.append("")
        for e in events[:20]:
            ts = e.get("created_at", "")
            if hasattr(ts, "strftime"):
                ts = ts.strftime("%H:%M:%S")
            lines.append(f"- `{ts}` [{e.get('severity', 'info')}] {e.get('event_type', '')}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Research OS v0.1.0*")

    return "\n".join(lines)


async def generate_json_export(
    run: dict[str, Any],
    hypotheses: list[dict[str, Any]],
    papers: list[dict[str, Any]],
) -> str:
    """Generate JSON data export."""
    export_data = {
        "run": {
            "id": str(run.get("id", "")),
            "title": run.get("title"),
            "topic": run.get("topic"),
            "status": run.get("status"),
            "goal_type": run.get("goal_type"),
            "created_at": run.get("created_at").isoformat() if run.get("created_at") else None,
        },
        "papers": [
            {
                "id": str(p.get("id", "")),
                "title": p.get("canonical_title") or p.get("title"),
                "doi": p.get("doi"),
                "arxiv_id": p.get("arxiv_id"),
                "year": p.get("publication_year"),
                "venue": p.get("venue"),
                "citation_count": p.get("citation_count", 0),
                "is_oa": p.get("is_oa", False),
            }
            for p in papers
        ],
        "hypotheses": [
            {
                "id": str(h.get("id", "")),
                "title": h.get("title"),
                "statement": h.get("statement"),
                "type": h.get("type"),
                "status": h.get("status"),
                "novelty_score": h.get("novelty_score"),
                "feasibility_score": h.get("feasibility_score"),
            }
            for h in hypotheses
        ],
    }
    return json.dumps(export_data, indent=2, ensure_ascii=False, default=str)


async def generate_csv_export(papers: list[dict[str, Any]]) -> str:
    """Generate CSV paper table."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Title", "DOI", "arXiv ID", "Year", "Venue",
        "Citations", "Is OA", "OA URL",
    ])
    for p in papers:
        writer.writerow([
            p.get("canonical_title") or p.get("title", ""),
            p.get("doi", ""),
            p.get("arxiv_id", ""),
            p.get("publication_year", ""),
            p.get("venue", ""),
            p.get("citation_count", 0) or 0,
            "Yes" if p.get("is_oa") else "No",
            p.get("oa_url", ""),
        ])
    return output.getvalue()


async def generate_bibtex_export(papers: list[dict[str, Any]]) -> str:
    """Generate BibTeX citations."""
    entries = []
    for i, p in enumerate(papers):
        # Generate a citation key
        title_words = (p.get("canonical_title") or "unknown").split()[:2]
        year = p.get("publication_year", "0000")
        key = f"{''.join(w.lower()[:5] for w in title_words)}{year}_{i}"
        key = "".join(c for c in key if c.isalnum() or c == "_")

        entry_lines = [f"@article{{{key},"]
        if p.get("canonical_title") or p.get("title"):
            entry_lines.append(f"  title = {{{p.get('canonical_title') or p.get('title')}}},")
        if p.get("venue"):
            entry_lines.append(f"  journal = {{{p['venue']}}},")
        if p.get("publication_year"):
            entry_lines.append(f"  year = {{{p['publication_year']}}},")
        if p.get("doi"):
            entry_lines.append(f"  doi = {{{p['doi']}}},")
        if p.get("arxiv_id"):
            entry_lines.append(f"  eprint = {{{p['arxiv_id']}}},")
            entry_lines.append(f"  archiveprefix = {{arXiv}},")
        entry_lines.append("}")
        entries.append("\n".join(entry_lines))

    return "\n\n".join(entries)
